#!/usr/bin/env bash
#
# start-lan-server.sh
# --------------------------------------------------------------------------
# Turns this Mac into a TEMPORARY local server for 9XAIPal so another PC on
# the same Wi-Fi/LAN can reach it for testing.
#
#   • Brings up the full Docker stack (API + UI on one port, Postgres, Redis,
#     SearXNG, Celery worker) and builds the React SPA.
#   • Removes the 100 MB upload cap so a 700-page PDF uploads with no size
#     limit, no proxy in the path, and no HTTP timeout (heavy extraction runs
#     asynchronously in the Celery worker, so the upload request itself is
#     short).
#   • Prints the exact URL to open from your other PC.
#   • On Ctrl+C, `q`, or closing the terminal, it tears the whole stack down
#     (`docker compose down`) so nothing keeps listening — your data volumes
#     are preserved, only the running containers/port go away.
#
# Run it manually:   ./start-lan-server.sh
# --------------------------------------------------------------------------

set -euo pipefail

# --- Locate the compose project (this script lives next to docker-compose.yml).
# Override with NINEX_BACKEND_DIR=/path ./start-lan-server.sh if you move it.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_DIR="${NINEX_BACKEND_DIR:-$SCRIPT_DIR}"

if [[ ! -f "$COMPOSE_DIR/docker-compose.yml" ]]; then
  echo "ERROR: docker-compose.yml not found in $COMPOSE_DIR" >&2
  echo "       Put this script in the backend/ folder, or set NINEX_BACKEND_DIR." >&2
  exit 1
fi
cd "$COMPOSE_DIR"

PORT="${API_PORT:-8000}"
# 100 GB cap == effectively no limit for any book PDF.
MAX_UPLOAD_MB="${MAX_UPLOAD_MB:-102400}"

# A throwaway override so we DON'T edit the tracked compose file or clobber any
# existing docker-compose.override.yml. Passed explicitly with -f below.
OVERRIDE_FILE="$(mktemp -t 9xaipal-lan-override.XXXXXX.yml)"

# Helper: always drive compose with the same file set + the "server" profile
# (the profile pulls in the one-shot frontend-build that produces the SPA).
compose() {
  docker compose -f docker-compose.yml -f "$OVERRIDE_FILE" --profile server "$@"
}

CLEANED=0
cleanup() {
  # Guard against running twice (INT fires, then EXIT fires).
  if [[ "$CLEANED" == "1" ]]; then return; fi
  CLEANED=1
  echo ""
  echo "==> Shutting the server down (containers + open port)..."
  # No -v: keep Postgres/Redis/SPA volumes (your uploaded papers & data persist).
  compose down --remove-orphans || true
  rm -f "$OVERRIDE_FILE"
  echo "==> Server stopped. Nothing is listening on port ${PORT} anymore."
}
# Covers Ctrl+C (INT), kill (TERM), terminal close (HUP), and normal exit.
trap cleanup INT TERM HUP EXIT

# --- Preflight: Docker must be running.
if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker isn't running. Start Docker Desktop and re-run." >&2
  exit 1
fi

# --- Detect this Mac's LAN IP (the address your other PC will use).
detect_ip() {
  local ip=""
  for iface in en0 en1 en2; do
    ip="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
    [[ -n "$ip" ]] && { echo "$ip"; return; }
  done
  # Fallback: ask the routing table which source IP reaches the internet.
  ip="$(route -n get default 2>/dev/null | awk '/interface:/{print $2}' \
        | xargs -I{} ipconfig getifaddr {} 2>/dev/null || true)"
  echo "$ip"
}
LAN_IP="$(detect_ip)"
[[ -z "$LAN_IP" ]] && LAN_IP="<this-mac-ip>"

# --- Write the upload-limit override.
cat > "$OVERRIDE_FILE" <<YAML
# Auto-generated by start-lan-server.sh — safe to delete.
services:
  api:
    environment:
      MAX_UPLOAD_SIZE_MB: "${MAX_UPLOAD_MB}"
  celery_worker:
    # Build the worker from the MinerU-enabled image (layout + OCR + tables +
    # math). The api stays on the slim image; only the worker extracts PDFs.
    build:
      context: .
      dockerfile: Dockerfile.mineru
    environment:
      # Use the modern \`mineru\` CLI (the compose default is the legacy
      # \`magic-pdf\` name, which doesn't exist in MinerU 2.x/3.x).
      MINERU_BINARY: "mineru"
      MINERU_LANG: "${MINERU_LANG:-en}"
      # A 700-page book on CPU-only Docker can take hours; don't let the
      # extractor's wall-clock timeout kill it.
      MINERU_TIMEOUT_SEC: "${MINERU_TIMEOUT_SEC:-14400}"
      MAX_UPLOAD_SIZE_MB: "${MAX_UPLOAD_MB}"
      # Pipeline models are pre-baked into Dockerfile.mineru. This signal
      # tells mineru_client.py to skip the HF_HUB_OFFLINE=1 toggle (which
      # otherwise blocks MinerU's post-processing stage — manifests as
      # "All connection attempts failed" on extraction).
      MINERU_BAKED_INTO_IMAGE: "1"
YAML

echo "============================================================"
echo " 9XAIPal — temporary LAN server"
echo "============================================================"
echo " Upload limit raised to ${MAX_UPLOAD_MB} MB (≈ no limit)."
echo " Starting the stack and building the UI (first run is slower)..."
echo ""

# Clear any previous instance first. The services use fixed container_names, so
# a leftover container from an earlier/aborted run (or one started by hand)
# would otherwise collide with "container name already in use". This is a no-op
# on a clean machine and preserves data volumes (no -v).
echo "==> Clearing any previous instance..."
compose down --remove-orphans >/dev/null 2>&1 || true
# Belt-and-suspenders: drop any stray containers using our fixed names, even if
# they belong to a different compose context.
docker rm -f 9xaipal-api 9xaipal-celery-worker 9xaipal-postgres \
              9xaipal-redis 9xaipal-searxng 9xaipal-frontend-build >/dev/null 2>&1 || true

# Bring everything up. --build is required so the worker picks up the
# MinerU image (Dockerfile.mineru); Docker layer-caches it after the first run.
compose up -d --build --remove-orphans

# --- Wait for the SPA build (one-shot) to finish, so the page is actually there.
echo "==> Building/serving the React UI..."
compose wait frontend-build >/dev/null 2>&1 || true

# --- Wait for the API to report healthy.
echo -n "==> Waiting for the API to come up"
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:${PORT}/api/v1/health" >/dev/null 2>&1; then
    break
  fi
  echo -n "."
  sleep 2
done
echo ""

HEALTH="$(curl -fsS "http://localhost:${PORT}/api/v1/health" 2>/dev/null || echo '{}')"
if ! echo "$HEALTH" | grep -q '"status":"ok"'; then
  echo "WARNING: API health is not fully OK yet: $HEALTH" >&2
  echo "         (It may still come up — check the logs below.)" >&2
fi

echo ""
echo "============================================================"
echo "  SERVER IS LIVE"
echo "------------------------------------------------------------"
echo "  On THIS Mac:        http://localhost:${PORT}"
echo "  From your other PC: http://${LAN_IP}:${PORT}"
echo ""
echo "  Health: ${HEALTH}"
echo ""
echo "  Both machines must be on the SAME Wi-Fi/network."
echo "  If the other PC can't connect, allow incoming connections"
echo "  for Docker in: System Settings > Network > Firewall."
echo ""
echo "  Press Ctrl+C (or close this terminal) to STOP the server."
echo "============================================================"
echo ""
echo "==> Live logs (api + worker). Ctrl+C to shut everything down:"
echo ""

# Block here streaming logs. Ctrl+C / terminal-close triggers the trap above,
# which runs `docker compose down`. `|| true` so the interrupt doesn't make
# `set -e` skip our cleanup.
compose logs -f api celery_worker || true
