#!/usr/bin/env python3
"""Install queue compatibility on a restored tree before consumers start.

Usage: prepare-celery-rollback.py NEW_TREE RESTORED_TREE
Only local files are used. Failure aborts deployment before consumers start.
The restored revision's PDF/English extraction pipeline is retained.
"""
import ast
from pathlib import Path
import shutil
import sys


def function_source(source, name, decorators=False):
    node = next(n for n in ast.parse(source).body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name == name)
    lines = source.splitlines(keepends=True)
    start = min([node.lineno] + [n.lineno for n in node.decorator_list]) if decorators else node.lineno
    return (start, node.end_lineno), ''.join(lines[start - 1:node.end_lineno])


def replace_function(old, new, name, decorators=False):
    _, replacement = function_source(new, name, decorators)
    try:
        (start, end), _ = function_source(old, name, decorators)
    except StopIteration:
        return old + '\n\n' + replacement + '\n'
    lines = old.splitlines(keepends=True)
    return ''.join(lines[:start-1]) + replacement + '\n' + ''.join(lines[end:])


def queue_schema(source):
    tree = ast.parse(source)
    function = next(n for n in tree.body if isinstance(n, ast.AsyncFunctionDef) and n.name == '_ensure_recent_columns')
    values = next(n.value for n in ast.walk(function) if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'critical_alters' for t in n.targets))
    return [node.value for node in values.elts if isinstance(node, ast.Constant) and isinstance(node.value, str) and any(name in node.value for name in ('execution_', 'claim_', 'ingestion_executions', 'reading_order_executions'))]


def prepare(source, target):
    source, target = Path(source), Path(target)
    workers = target / 'backend/app/workers'
    for name in ('execution_claims.py', 'owned_subprocess.py', 'forwarding.py', 'rollback_compatibility.py'):
        shutil.copyfile(source / 'backend/app/workers' / name, workers / name)

    # A deploy can fail before the new API ever applies migrations. Carry
    # only queue-claim DDL into the old API's migration path and worker startup.
    statements = queue_schema((source / 'backend/app/database/migrations.py').read_text())
    migrations = target / 'backend/app/database/migrations.py'
    old = migrations.read_text()
    marker = '    critical_alters = [\n'
    if old.count(marker) != 1:
        raise RuntimeError('Unknown migration path; refusing unfenced rollback')
    migrations.write_text(old.replace(marker, marker + ''.join(f'        {sql!r},\n' for sql in statements), 1))
    (workers / 'rollback_schema.py').write_text(
        '# Queue compatibility schema; generated by prepare-celery-rollback.py.\n'
        f'STATEMENTS = {statements!r}\n'
        'def ensure():\n'
        '    from sqlalchemy import text\n'
        '    from app.database.connection import sync_engine\n'
        '    with sync_engine.begin() as connection:\n'
        '        connection.execute(text("SELECT pg_advisory_xact_lock(hashtext(\'9xaipal:rollback-schema\'))"))\n'
        '        for statement in STATEMENTS:\n'
        '            connection.execute(text(statement))\n'
    )

    app = target / 'backend/app/core/celery_app.py'
    tasks = workers / 'tasks.py'
    old_tasks = tasks.read_text()
    if 'task_routes' in app.read_text() and 'ingest' in app.read_text():
        # Queue-aware revisions already have separate worker roles. Retain
        # those roles and install current guards/handoff without double wrapping.
        current_tasks = (source / 'backend/app/workers/tasks.py').read_text()
        for name in ('process_ingestion', 'reconstruct_reading_order', 'process_article_ingestion'):
            old_tasks = replace_function(old_tasks, current_tasks, name, decorators=True)
        if 'from app.workers.execution_claims import HeavyTask, guarded_heavy' not in old_tasks:
            old_tasks = old_tasks.replace('from app.core.celery_app import celery_app', 'from app.core.celery_app import celery_app\nfrom app.workers.execution_claims import HeavyTask, guarded_heavy', 1)
        pipeline = target / 'backend/app/extraction/pipeline_sync.py'
        old = pipeline.read_text()
        current = (source / 'backend/app/extraction/pipeline_sync.py').read_text()
        names = ('_adopt_pdf_from_url', '_commit_url_pdf', '_publish_adopted_pdf', '_serialized_url_import', '_check_article_owner', '_fail_article', 'run_article_pipeline_sync')
        # Install the whole article group in dependency order. Earlier split
        # trees lack the decorator: appending it after its use breaks import.
        for name in (*names, '_store_url_pdf_once'):
            try:
                (start, end), _ = function_source(old, name, decorators=True)
                lines = old.splitlines(keepends=True)
                old = ''.join(lines[:start-1]) + ''.join(lines[end:])
            except StopIteration:
                pass
        old += '\n\n' + '\n\n'.join(function_source(current, name, decorators=True)[1] for name in names) + '\n'
        # These helpers may be absent from an early split revision. Insert
        # their imports after the module docstring/future imports.
        body = ast.parse(old).body
        insertion = 0
        for node in body:
            if (isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str)) or (isinstance(node, ast.ImportFrom) and node.module == '__future__'):
                insertion = node.end_lineno
            else:
                break
        lines = old.splitlines(keepends=True)
        old = ''.join(lines[:insertion]) + '\nimport fcntl\nimport hashlib\nimport os\nimport tempfile\nfrom functools import wraps\nfrom sqlalchemy import event\n' + ''.join(lines[insertion:])
        pipeline.write_text(old)
        # Retain queue-scoped restore and ingest-only scratch startup in early
        # split revisions, which originally had neither guard nor worker roles.
        core = app.read_text()
        current_core = (source / 'backend/app/core/celery_app.py').read_text()
        for name in ('_sweep_extraction_scratch', '_restore_interrupted_tasks'):
            core = replace_function(core, current_core, name, decorators=True)
        if 'import os\n' not in core:
            core = core.replace('import json\n', 'import json\nimport os\n', 1)
        app.write_text(core)
        for filename in ('docker-compose.prod.yml', 'docker-compose.yml'):
            compose = target / 'backend' / filename
            if not compose.exists():
                continue
            config = compose.read_text()
            if 'WORKER_ROLE:' not in config:
                start = config.index('  celery_worker:')
                end = config.index('  celery_worker_light:')
                worker = config[start:end]
                if worker.count('    environment:\n') != 1:
                    raise RuntimeError('Unknown worker environment; refusing unsafe rollback')
                worker = worker.replace('    environment:\n', '    environment: &rollback-worker-environment\n      WORKER_ROLE: ingest\n', 1)
                config = config[:start] + worker + config[end:]
                config = config.replace('  celery_worker_light:\n', '  celery_worker_light:\n    environment:\n      <<: *rollback-worker-environment\n      WORKER_ROLE: light\n', 1)
                compose.write_text(config)
    elif 'execution_generation' not in function_source(old_tasks, 'process_ingestion')[1]:
        header = 'def process_ingestion(self, document_id: str, job_id: str, filename: str) -> dict:'
        if old_tasks.count(header) != 1:
            raise RuntimeError('Unknown ingestion task signature; refusing unfenced rollback')
        old_tasks = old_tasks.replace(header, 'def process_ingestion(self, document_id: str, job_id: str, filename: str, *, execution_generation: int = 0) -> dict:')
    tasks.write_text(old_tasks)

    services = target / 'backend/app/services/ingestion.py'
    services.write_text(replace_function(services.read_text(), (source / 'backend/app/services/ingestion.py').read_text(), 'requeue_failed_job'))
    endpoint = target / 'backend/app/api/v1/endpoints/documents.py'
    old = endpoint.read_text()
    original = 'str(paper_id), str(queued_job["id"]), document["filename"]\n'
    if 'execution_generation=queued_job["execution_generation"]' not in old:
        if old.count(original) != 1:
            raise RuntimeError('Unknown confirmation dispatch shape; refusing unfenced rollback')
        endpoint.write_text(old.replace(original, 'str(paper_id), str(queued_job["id"]), document["filename"],\n            execution_generation=queued_job["execution_generation"],\n'))
    registration = '\nimport app.workers.rollback_compatibility  # rollback consumer fencing\n'
    if registration.strip() not in app.read_text():
        with app.open('a') as output:
            output.write(registration)
    print('Installed rollback consumer fencing; PDF extraction remains from the restored revision')


if __name__ == '__main__':
    prepare(*sys.argv[1:])
